ChaDB=[
{
Name:"ミコト",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"火",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-_Szs-m1yWUw/W68Xeq4tFpI/AAAAAAAABXE/GdpBZGeLbTAFlEwm7JZfV_gL1DmTb63DwCE0YBhgL/s1024/IMG_1277.PNG" width="96"/>',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:['<img class="magnifiable" src="https://lh3.googleusercontent.com/-KOKBLmiyX9c/W682sbE7iII/AAAAAAAABXo/cJQNOnRryeoOxuFG-nzNLsjr7xpiGfG8QCE0YBhgL/s1024/IMG_1284.PNG" width="96" />','<img class="magnifiable" src="https://lh3.googleusercontent.com/-TYV6_aL0w08/W69QvnFuONI/AAAAAAAABZ0/ajtCjNp8VLcvV0tsjU48gBArpWVqHdCDQCE0YBhgL/s1024/IMG_1289.PNG" width="96"/>','<img class="magnifiable" src="https://lh3.googleusercontent.com/-KOKBLmiyX9c/W682sbE7iII/AAAAAAAABXo/cJQNOnRryeoOxuFG-nzNLsjr7xpiGfG8QCE0YBhgL/s1024/IMG_1284.PNG" width="96" />'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-7RnDRY0UXfE/W69Q45diwSI/AAAAAAAABZ0/W3R5c_jfOHEi84ZKb1hDM65VOtfMTW7MwCE0YBhgL/s1024/IMG_1290.PNG" width="64"/>',
chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-3R8uKG_-VXU/W69Qzq-XDGI/AAAAAAAABZ0/Swa2ocX4hiYVLC8CTh8nGooU9DkHFj_LQCE0YBhgL/s1024/IMG_1286.PNG" />',
DchaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-JEaH1oKCmuw/W69QzglPfhI/AAAAAAAABZ0/_puTG_eb5IIlSaQ0hwm7NlkXwFTAlWvAwCE0YBhgL/s1024/IMG_1287.PNG" />',
skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-5_PPXu9PfyQ/W69QvrnfEII/AAAAAAAABZ0/4Ev3jYPrC7sPEqzWS-GObooHCf18WAhpgCE0YBhgL/s1024/IMG_1288.PNG" width="96"/>',
skil2Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-Cs9v8iWPSsA/W67sMn18paI/AAAAAAAABWg/-vOtrxsvsIEL2_JzgzB_1moKvvwnddo0QCE0YBhgL/s1024/IMG_1271.PNG" width="96"/>',
URL:'https://www.dragaliguide.com/entry/2018/09/29/【ドラガリアロスト】ミコトの評価とアビリティ'
},
{
Name:"エゼリット",
Name2:"ブリリアントジーニアス 光輝の天才",
get:"可",
attribute:"火",
rare:"5",
date:"2018.9.27",
type:"補助",
ste:["sen","HP","kougei"],
job:"短剣",
Rank:"S",
reRank:"S",
skil1:"ランブリングミーティア",
skil1Detail:"前方の敵に火属性のダメージを与える。攻撃時、移動操作が可能",
skil2:"ブリリアントインフェルノ",
skil2Detail:"15秒間【インフェルノモード】を発動。【インフェルノモード】中は自身の攻撃力が10%アップし、通常攻撃に防御力をダウンさせる効果が付与される。",
exAbi:"クリティカル率+5%",
exAbiDetail:"パーティ全員のクリティカル確率が5%アップする。",
exSrc:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-KOKBLmiyX9c/W682sbE7iII/AAAAAAAABXo/cJQNOnRryeoOxuFG-nzNLsjr7xpiGfG8QCE0YBhgL/s1024/IMG_1284.PNG" width="96" />',
Abi:["疾風怒濤・弱体+15%","睡眠耐性+50%","ブレイク特攻+25%"],
AbiSrc:['<img class="magnifiable" src="https://lh3.googleusercontent.com/-_Szs-m1yWUw/W68Xeq4tFpI/AAAAAAAABXE/GdpBZGeLbTAFlEwm7JZfV_gL1DmTb63DwCE0YBhgL/s1024/IMG_1277.PNG" width="96"/>','<img class="magnifiable" src="https://lh3.googleusercontent.com/-GChOaYNmMMY/W68XemVtU_I/AAAAAAAABXE/5LWAWcmpl20SP6OjUm-kXrcnTDFI-VeqACE0YBhgL/s1024/IMG_1278.PNG" width="96"/>','<img class="magnifiable" src="https://lh3.googleusercontent.com/-9-CGLJCpgS8/W68Xeux3bqI/AAAAAAAABXE/BQ2dvI6i3yQmWZ1helFugW_xcAwmAjbNACE0YBhgL/s1024/IMG_1279.PNG" width="96"/>'],
AbiD:['ヒット数15以上で、敵にデバフを与える確率が15%アップする','「睡眠状態」になる確率が50%ダウンする','ブレイク中の敵へ与えるダメージが25%アップする'],
sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-ShaTpwXwzJI/W69EPROLgoI/AAAAAAAABY0/dLDvGekgItkCcjCbvvaobB4diRZyv9I2wCE0YBhgL/s1024/IMG_1285.PNG" width="64"/>',
chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-iaFTJ7dHgrM/W67rkIpGvxI/AAAAAAAABWM/w0TNXp--uyUTYVY0emrh3dvjaAfwm-sugCE0YBhgL/s1024/IMG_1275.PNG" />',
DchaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-UHCZuMecKrw/W67rkI0zoVI/AAAAAAAABWM/nbDvPd8o2rY3qTkUSoG3rf0R_OIGnvsFACE0YBhgL/s1024/IMG_1276.PNG" />',
skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-C6c8XaCReCM/W67sMh-ALSI/AAAAAAAABWg/k9VTrqoVlSkC3UoU84VTrugBjDN1JrhPwCE0YBhgL/s1024/IMG_1270.PNG" width="96"/>',
skil2Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-Cs9v8iWPSsA/W67sMn18paI/AAAAAAAABWg/-vOtrxsvsIEL2_JzgzB_1moKvvwnddo0QCE0YBhgL/s1024/IMG_1271.PNG" width="96"/>',
URL:'https://www.dragaliguide.com/entry/2018/09/29/【ドラガリアロスト】エゼリットの評価とアビリ'
},
{
Name:"アレクシス",
Name2:"コンクエストキング 覇心の王",
get:"可",
attribute:"水",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"剣",
Rank:"S",
reRank:"S",
skil1:"マジェスティックタイド",
skil1Detail:"直線上の敵に水属性のダメージを与える。自身にかかっているバフの数だけ【ブースト】がかかり、与えるダメージが増える。",
skil2:"ロイヤルメイルシュトローム",
skil2Detail:"周囲の敵に水属性のダメージを与える。",
exAbi:"竜化ブースト+8％",
exAbiDetail:"パーティ全員の竜化ゲージ上昇率が8％アップする",
exSrc:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-IL80t-O-GH4/W6-Prhc9M4I/AAAAAAAABaw/pZiBJVf2E6w_bdjkvlOT00cm6EAleEAmwCE0YBhgL/s1024/IMG_1296.PNG" width="96" />',
Abi:["バースト撃破・攻+5％","気絶耐性+50%","バーストダメージ+40％"],
AbiSrc:['<img class="magnifiable" src="https://lh3.googleusercontent.com/-KOKBLmiyX9c/W682sbE7iII/AAAAAAAABXo/cJQNOnRryeoOxuFG-nzNLsjr7xpiGfG8QCE0YBhgL/s1024/IMG_1284.PNG" width="96" />','<img class="magnifiable" src="https://lh3.googleusercontent.com/-TYV6_aL0w08/W69QvnFuONI/AAAAAAAABZ0/ajtCjNp8VLcvV0tsjU48gBArpWVqHdCDQCE0YBhgL/s1024/IMG_1289.PNG" width="96"/>','<img class="magnifiable" src="https://lh3.googleusercontent.com/-SWzuHxmV9UE/W6-PropafMI/AAAAAAAABaw/wtj0NKvbkGsScPA_8Y-ivTds--VGlWN3QCE0YBhgL/s1024/IMG_1297.PNG" width="96"/>'],
AbiD:['バーストアタックで敵を3体倒すたびに攻撃力が5％アップする。この効果は1クエスト5回まで発動する。','「気絶」状態になる確率が50％ダウンする。','バーストアタックのダメージが40％アップする。'],
sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-t4YgThGg9wo/W6-DIjOVy5I/AAAAAAAABaU/QQKg4lcOMGIBKXeO22CXvGZAVC64p3YUQCE0YBhgL/s1024/IMG_1291.PNG" width="64"/>',
chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-I7OyhzRbm2Q/W6-DIsVbSnI/AAAAAAAABaM/groPe7eAqqIaZ35_L-wBz8JvBDn4NZDIwCE0YBhgL/s1024/IMG_1292.PNG" />',
DchaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-FRyLrCsWsJ4/W6-DIi4s50I/AAAAAAAABaM/gDFp7Oq2pPk-nkfSOvEzyBZcBTHdbC7kgCE0YBhgL/s1024/IMG_1293.PNG" />',
skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-ZXWK-VAxvs0/W6-Prp8fm3I/AAAAAAAABaw/3I6lv-FqIa8zv7H92_NX9sL1A6Yb-SOFQCE0YBhgL/s1024/IMG_1294.PNG" width="96"/>',
skil2Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-uoI1HYTafmk/W6-PrgIh46I/AAAAAAAABaw/3zn4-wHvl60Os7r-wJqw2TQq5Lmm2eCBQCE0YBhgL/s1024/IMG_1295.PNG" width="96"/>',
URL:'https://www.dragaliguide.com/entry/2018/09/29/【ドラガリアロスト】アレクシスの評価とアビリ'
},
    {
Name:"ザインフラッド",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"水",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
},
    {
Name:"ホーク",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"風",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
},
    {
Name:"メリィベル",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"風",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
},
    {
Name:"ジュリエッタ",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"風",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
},
    {
Name:"ヒルデガルト",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"風",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
},
    {
Name:"ネファリエ",
Name2:"アメツチマスター 森羅伴生",
get:"可",
attribute:"風",
rare:"5",
date:"2018.9.27",
type:"攻撃",
ste:["sen","HP","kougei"],
job:"刀",
Rank:"S",
reRank:"S",
skil1:"熾炎剣・魔障覆滅",
skil1Detail:"前方の敵に火属性のダメージを与える。敵にヒットさせると【構え】が発動。【構え】中は、攻撃力がアップし、スキルが強化される。【構え】は2段階目にスキルをヒットさせるか、時間経過で解除。",
skil2:"熾炎剣・胸中燈火",
skil2Detail:"10秒間、自身の攻撃速度を15%アップする。",
exAbi:"攻撃力+5%",
exAbiDetail:"パーティ全員の攻撃力が5%アップする。",
exSrc:' width="96" />',
Abi:["HP70%で会心+8%","気絶耐性+50%","クリティカル率+6%"],
AbiSrc:[' width="96"/>',' width="96"/>',' width="96"/>'],
AbiD:['HP70％以上で攻撃がクリティカルになる確率が8％アップする。','「気絶」状態になる確率が50％ダウンする。','攻撃がクリティカルになる確率が6％アップする。'],
sortPicture:' width="64"/>',
chaPicture:'',
DchaPicture:'',
skil1Picture:' width="96"/>',
skil2Picture:' width="96"/>',
URL:''
}
];
