BukiDB=[
{
  Name:"ナイツソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"7",minAt:"25",MinSe:"32",maxHp:"24",maxAt:"86",MaxSe:"110"},
  skilP:"0",
  skil1:"なし",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-t78wxyAsu9k/W7Hq590oovI/AAAAAAAABsA/byySZJd6UWEcrWtiQwIrJXgFhKf01LQMQCE0YBhgL/s1024/IMG_1406.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-cnfrTnjBMRY/W7HrOY6I89I/AAAAAAAABsg/DXzU1Md7O-Qa06Fi5Tk65squa1RSkOefQCE0YBhgL/s1024/IMG_1195-3.PNG" itemprop="image">',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:'https://www.dragaliguide.com/entry/2018/10/01/【ドラガリアロスト】ナイツソードの評価とステ'
},
  {
  Name:"ワイドソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"5",
  skil1:"ワイドブレイク",
  skil1Detail:"前方の敵にダメージを与える",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-bgsj6DNLj4A/W7Hq50pWPUI/AAAAAAAABsA/yS8Cs1ddP34zpjKxLG7l4wH1-e4aCYl3ACE0YBhgL/s1024/IMG_1407.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-UeNhJDPEVmg/W7Kcdh08AQI/AAAAAAAABtc/Zhh9rgAC3vci0KDw1d0qe35gFdRUY6LKgCE0YBhgL/s1024/IMG_1195-3.PNG" itemprop="image">',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-L43ju-xAhm8/W7EZNnkSdII/AAAAAAAABl4/ZOFJzjWrkTEwpUZWlTv-C3wFEIhQjtm7gCE0YBhgL/s1024/IMG_1326.png" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:'https://www.dragaliguide.com/entry/2018/10/02/【ドラガリアロスト】ワイドソードの評価とステ'
},
{
  Name:"エンチャントソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"7",
  skil1:"エンチャントスラッシュ",
  skil1Detail:"周囲の敵にダメージを与える",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-cW_BSrzB90Q/W7Hq59YtxUI/AAAAAAAABsA/Rut8gzsyCYYKkG5ojNbPieYkitnD_J1awCE0YBhgL/s1024/IMG_1408.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-amit9QVh-uI/W7Kebh8ByuI/AAAAAAAABts/z5Z7ARNIaXgz_XIjerHGIcE1x7bfvUpgwCE0YBhgL/s1024/IMG_1195-3.PNG" itemprop="image">',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-uoI1HYTafmk/W6-PrgIh46I/AAAAAAAABaw/3zn4-wHvl60Os7r-wJqw2TQq5Lmm2eCBQCE0YBhgL/s1024/IMG_1295.PNG" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"ハードヒートソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"5",
  skil1:"ヒートブレイク",
  skil1Detail:"前方の敵に火属性のダメージを与える。",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-Vl-tN2HbCL4/W7Hq3VWZNlI/AAAAAAAABrw/0cXL9QpCeyAfcogM4UiGObBVgTj7mINNACE0YBhgL/s1024/IMG_1409.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/--LUdcGRKHCk/W7KegMWL9ZI/AAAAAAAABt4/K4NM9PjSgq04hvKy1eT5IdPZa6t15dmbQCE0YBhgL/s1024/IMG_1195-3.PNG" itemprop="image">',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-L43ju-xAhm8/W7EZNnkSdII/AAAAAAAABl4/ZOFJzjWrkTEwpUZWlTv-C3wFEIhQjtm7gCE0YBhgL/s1024/IMG_1326.png" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"フェザーソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"5",
  skil1:"フェザーブレイク",
  skil1Detail:"前方の敵に火属性のダメージを与える。",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-DAQtNqd4pbY/W7Hq3b005yI/AAAAAAAABrw/2cewJ7tmeX4B1fBVtj3ZFQ2NoVkU-gmBACE0YBhgL/s1024/IMG_1410.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-pDflaiXsEJo/W7KgzEqH2sI/AAAAAAAABuQ/QnEwPc2prIQuRUSGZdevQ-lVdUyH14EQACE0YBhgL/s1024/IMG_1195-3.PNG" />',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-L43ju-xAhm8/W7EZNnkSdII/AAAAAAAABl4/ZOFJzjWrkTEwpUZWlTv-C3wFEIhQjtm7gCE0YBhgL/s1024/IMG_1326.png" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"ブラッドソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"5",
  skil1:"ブラッドブレイク",
  skil1Detail:"前方の敵に火属性のダメージを与える。",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-qEfhY-IapOU/W7Hq3aYAAJI/AAAAAAAABrw/MbeBsY4Y6jITsfFq1big-3ZMlX6XtACvQCE0YBhgL/s1024/IMG_1411.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-0QqLaeCzHXs/W7Kg4Je2JGI/AAAAAAAABuc/4bNwNqtSKcgFMbUtbF2jdFgjSEplpSekgCE0YBhgL/s1024/IMG_1195-3.PNG" />',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-L43ju-xAhm8/W7EZNnkSdII/AAAAAAAABl4/ZOFJzjWrkTEwpUZWlTv-C3wFEIhQjtm7gCE0YBhgL/s1024/IMG_1326.png" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"レインソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"7",
  skil1:"レインスラッシュ",
  skil1Detail:"周囲の敵にダメージを与える",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-mpY5lrDup1I/W7Hq3VNy35I/AAAAAAAABrw/kpKBz5R0C90MIVqc5ZR148-9GX2hlYknQCE0YBhgL/s1024/IMG_1412.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-rGCVLELWX4k/W7Kg9otw2WI/AAAAAAAABuo/2bQB0CYMUasTOCBOpIOTieqW6s2efpP9wCE0YBhgL/s1024/IMG_1195-3.PNG" />',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-uoI1HYTafmk/W6-PrgIh46I/AAAAAAAABaw/3zn4-wHvl60Os7r-wJqw2TQq5Lmm2eCBQCE0YBhgL/s1024/IMG_1295.PNG" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"グラスソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"7",
  skil1:"グラススラッシュ",
  skil1Detail:"周囲の敵にダメージを与える",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-MP4AyO9s2E8/W7Hq3YUnksI/AAAAAAAABrw/HFyk5Fp5ovk4kD90246WgT64C1nt9AV7gCE0YBhgL/s1024/IMG_1414.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-xpydR562XCE/W7KhDLrkW_I/AAAAAAAABu0/I4ZyGRBKRRMiK7sUu0QE-EUPf2rcLxnOwCE0YBhgL/s1024/IMG_1195-3.PNG" />',
  skil1Picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-uoI1HYTafmk/W6-PrgIh46I/AAAAAAAABaw/3zn4-wHvl60Os7r-wJqw2TQq5Lmm2eCBQCE0YBhgL/s1024/IMG_1295.PNG" width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"フェザーソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:' width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
}
];
