BukiDB=[
{
  Name:"ナイツソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"7",minAt:"25",MinSe:"32",maxHp:"24",maxAt:"86",MaxSe:"110"},
  skilP:"0",
  skil1:"なし",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-t78wxyAsu9k/W7Hq590oovI/AAAAAAAABsA/byySZJd6UWEcrWtiQwIrJXgFhKf01LQMQCE0YBhgL/s1024/IMG_1406.PNG" width="64"/>',
  chaPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-cnfrTnjBMRY/W7HrOY6I89I/AAAAAAAABsg/DXzU1Md7O-Qa06Fi5Tk65squa1RSkOefQCE0YBhgL/s1024/IMG_1195-3.PNG" itemprop="image">',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:'https://www.dragaliguide.com/entry/2018/10/01/【ドラガリアロスト】ナイツソードの評価とステ'
},
  {
  Name:"ワイドソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-bgsj6DNLj4A/W7Hq50pWPUI/AAAAAAAABsA/yS8Cs1ddP34zpjKxLG7l4wH1-e4aCYl3ACE0YBhgL/s1024/IMG_1407.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"エンチャントソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-cW_BSrzB90Q/W7Hq59YtxUI/AAAAAAAABsA/Rut8gzsyCYYKkG5ojNbPieYkitnD_J1awCE0YBhgL/s1024/IMG_1408.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"ハードヒートソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-Vl-tN2HbCL4/W7Hq3VWZNlI/AAAAAAAABrw/0cXL9QpCeyAfcogM4UiGObBVgTj7mINNACE0YBhgL/s1024/IMG_1409.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"フェザーソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-DAQtNqd4pbY/W7Hq3b005yI/AAAAAAAABrw/2cewJ7tmeX4B1fBVtj3ZFQ2NoVkU-gmBACE0YBhgL/s1024/IMG_1410.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"ブラッドソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-qEfhY-IapOU/W7Hq3aYAAJI/AAAAAAAABrw/MbeBsY4Y6jITsfFq1big-3ZMlX6XtACvQCE0YBhgL/s1024/IMG_1411.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"レインソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-mpY5lrDup1I/W7Hq3VNy35I/AAAAAAAABrw/kpKBz5R0C90MIVqc5ZR148-9GX2hlYknQCE0YBhgL/s1024/IMG_1412.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"グラスソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-MP4AyO9s2E8/W7Hq3YUnksI/AAAAAAAABrw/HFyk5Fp5ovk4kD90246WgT64C1nt9AV7gCE0YBhgL/s1024/IMG_1414.PNG" width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
},
{
  Name:"フェザーソード",
  get:"可",
  maxLV:"40",
  job:"剣",
  rare:"3",
  attribute:"火",
  date:"2018.9.27",
  ste:{minHp:"",minAt:"",MinSe:"",maxHp:"",maxAt:"",MaxSe:"0"},
  skilP:"0",
  skil1:"-",
  skil1Detail:"-",
  skil2:"-",
  skil2Detail:"-",
  sortPicture:' width="64"/>',
  chaPicture:'',
  skil1Picture:' width="96"/>',
  skil2Picture:' width="96"/>',
  URL:''
}
];
