var musicDB=[
{
  musicName: "Perfect Shining!!",
  genre:"オンゲキ",
  class:"1-01-01",
  artist: "曲：宮崎誠 歌：星咲 あかり(CV:赤尾 ひかる)",
  BPM:"182",
  URL:"",
  musicTime:"2:23",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"チャプター:目指せ！いっぱいのエール！",
  musicDate:"2018.7.26",
  basicArray:["3","377","","","","","","47","",""],
  advancedArray:["6","565","","","","","","52","",""],
  expertArray:["8","605","","","","","","103","","ものくろっく"],
  masterArray:["11","918","","","","","","133","11.5","黒にするrioN"],
  picture:'<img class="magnifiable" src="https://lh3.googleusercontent.com/-rYziTw_sVeM/W5yUi6Q4WrI/AAAAAAAAAw4/OEQMf55VTAETYdRM2C_XGTShs2gYFhxVwCE0YBhgL/s1024/1532602274.jpg" />'
},
{
  musicName: "STARTLINER",
  genre:"オンゲキ",
  class:"1-01-01",
  artist: "曲：kz(livetune) 歌：オンゲキシューターズ",
  BPM:"135",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.2)",
  banMethod:"ジュエル3個消費",
  musicDate:"2018.7.26",
  basicArray:["2","369","","","","","","30","",""],
  advancedArray:["5","432","","","","","","38","",""],
  expertArray:["8+","832","","","","","","80","","ものくろっく"],
  masterArray:["11","819","","","","","","95","11.0","ロシェ＠ペンギン"],
  picture:''
},
{
  musicName: "君の知らない物語",
  genre:"POPS&ANIME",
  class:"1-01-01",
  artist: "supercell 「化物語」",
  BPM:"165",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"チャプター:目指せ！いっぱいのエール！",
  musicDate:"2018.7.26",
  basicArray:["2","220","","","","","","22","",""],
  advancedArray:["5","375","","","","","","44","",""],
  expertArray:["7+","394","","","","","","100","","ロシェ＠ペンギン＆ものくろっく"],
  masterArray:["11+","579","","","","","","58","10.4","ロシェ＠ペンギン"],
  picture:''
},
{
  musicName: "シュガーソングとビターステップ",
  genre:"",
  class:"1-01-01",
  artist: "UNISON SQUARE GARDEN",
  BPM:"132",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"チャプター:目指せ！いっぱいのエール！",
  musicDate:"2018.7.26",
  basicArray:["2","234","","","","","","43","",""],
  advancedArray:["5","376","","","","","","48","",""],
  expertArray:["7+","526","","","","","","123","","ロシェ＠ペンギン＆ものくろっく"],
  masterArray:["11+","976","","","","","","58","11.7","ものくろっく"],
  picture:''
},
{
  musicName: "檄!帝国華撃団",
  genre:"VARIETY",
  class:"1-01-01",
  artist: "真宮寺さくら（横山智佐）＆帝国歌劇団",
  BPM:"143",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"チャプター:目指せ！いっぱいのエール！",
  musicDate:"2018.7.26",
  basicArray:["2","278","","","","","","45","",""],
  advancedArray:["5","569","","","","","","55","",""],
  expertArray:["7+","633","","","","","","185","","ロシェ＠ペンギン＆ものくろっく"],
  masterArray:["11","817 ","","","","","","120","11.3","ロシェ＠ペンギン"],
  picture:''
},
{
  musicName: "回レ！雪月花",
  genre:"POPS&ANIME",
  class:"1-01-01",
  artist: "歌組雪月花 夜々(原田 ひとみ)いろり(茅野 愛衣)小紫(小倉 唯) ",
  BPM:"160",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"ジュエル10個消費",
  musicDate:"2018.7.26",
  basicArray:["3","270","","","","","","92","",""],
  advancedArray:["6","436","","","","","","66","",""],
  expertArray:["9","566","","","","","","126","","ロシェ＠ペンギン＆rioN"],
  masterArray:["12","1,087","","","","","","116","12.2","ロシェ回ペンギン"],
  picture:''
},
{
  musicName: "ＧＯ！ＧＯ！ラブリズム♥",
  genre:"チュウマイ",
  class:"1-01-01",
  artist: "片霧烈火オンザみんマンション",
  BPM:"176",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"ジュエル20個消費",
  musicDate:"2018.7.26",
  basicArray:["3","302","","","","","","87","",""],
  advancedArray:["6","576","","","","","","133","",""],
  expertArray:["9","685","","","","","","130","","ロシェ＠ペンギン＆ものくろっく"],
  masterArray:["12","1,170","","","","","","72","12.4","ものくろっく"],
  picture:''
},
{
  musicName: "",
  genre:"",
  class:"1-01-02",
  artist: "",
  BPM:"",
  URL:"",
  musicTime:"",
  chapter:"「目指せ！いっぱいのエール！」",
  Vscha:"星咲あかり(Lv.1)",
  banMethod:"チャプター:目指せ！いっぱいのエール！",
  musicDate:"2018.7.26",
  basicArray:["2","369","","","","","","47","",""],
  advancedArray:["5","432","","","","","","52","",""],
  expertArray:["8+","832","","","","","","103","","ものくろっく"],
  masterArray:["11","819","","","","","","133","11.0","黒にするrioN"],
  picture:''
}

];
